### ISSUE TITLE
TensorFlow errors with careless_zero.py

### ISSUE THREAD

**Issue by DorisMai** [Hekstra-Lab/careless-examples#11]
Sometimes careless_zero.py run into the following TensorFlow errors. The errors don't always occur, which makes them hard to reproduce and understand. I have seen it when running on a GPU with optimization steps=1000 and 10_000. When I adapt the script for my own data (small molecules, <5000 reflections), I have seen this error at steps < 100 on CPUs too. Do you have any insight on why they occur and how to fix them?

> Traceback (most recent call last):
>   File "/careless-examples/careless_zero/test_careless_zero.py", line 88, in <module>
>     optimizer.minimize(minus_elbo, weights)
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 526, in minimize
>     grads_and_vars = self.compute_gradients(loss, var_list, tape)
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/keras/optimizers/optimizer_experimental/optimizer.py", line 255, in compute_gradients
>     loss = loss()
>   File "/careless-examples/careless_zero/test_careless_zero.py", line 74, in minus_elbo
>     z = q.sample(mc_samples)
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py", line 1205, in sample
>     return self._call_sample_n(sample_shape, seed, **kwargs)
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow_probability/python/distributions/distribution.py", line 1182, in _call_sample_n
>     samples = self._sample_n(
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow_probability/python/distributions/truncated_normal.py", line 251, in _sample_n
>     return tf.random.stateless_parameterized_truncated_normal(
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
>     raise e.with_traceback(filtered_tb) from None
>   File "/home/anaconda3/envs/tf/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 7215, in raise_from_not_ok_status
>     raise core._status_to_exception(e) from None  # pylint: disable=protected-access
> tensorflow.python.framework.errors_impl.InvalidArgumentError: {{function_node __wrapped__StatelessParameterizedTruncatedNormal_device_/job:localhost/replica:0/task:0/device:CPU:0}} Invalid parameters [Op:StatelessParameterizedTruncatedNormal]

**Comment by kmdalton** [comment]
@DorisMai, this error is unfortunately one of the most common ones and it is not very diagnostic. It will happen any time any of the location / scale parameters of the surrogate posterior become NaN. Basically it just means there was some kind of numerical error in the previous gradient step. There could be a number of causes for this. I could speculate, but let me first ask: Why are you using `careless_zero.py` at all? Can you not use the `careless` command line interface for your project? Is there some feature missing? 

I took a lot more care in making sure that the CLI is numerically stable. You might have a better time with that. If you really need / want to use `careless_zero.py`, I can make some recommendations to improve stability. Let me know.

**Comment by DorisMai** [comment]
I am trying to use careless for small molecules data, and we typically use shelx to solve and refine structures. This means that I want the output to be in shelx hkl format and ideally intensities rather than amplitude data. I am having trouble converting the .mtz output from running careless commandline into the kind of .hkl file I want using mtz2hkl from CCP4 -- specifically I am testing if I can get similar results compared to the workflow of XDS --> shelx. 

I was about to open an issue on this in the careless depository -- do you have any suggestion on this?

**Comment by kmdalton** [comment]
I think it is better for you to run the careless CLI. That way you have access to new features like image layers and multivariate priors plus a (hopefully) more stable interface. The mtz2hkl problem seems solvable. However, I am not sure I am the best one to help on that front. I don't really use SHELX in my own work. Our package, [reciprocalspaceship](https://github.com/rs-station/reciprocalspaceship), should make it pretty easy to make a conversion script though. I would poke around over there. From my end, I can add intensity columns to the careless output. Frankly, I'm not sure why I never thought to do that before.

**Comment by kmdalton** [comment]
I'll try to get the intensities implemented soon. You can look for updates on this issue: https://github.com/rs-station/careless/issues/90#issue-1646460427

**Comment by kmdalton** [comment]
Okay --- the current careless main should output intensities. Let me know if you run into issues. I'll try to do a new pypi release tomorrow.

**Comment by kmdalton** [comment]
v0.2.9 on PyPI will output intensities now. If you want help converting the output from `mtz` to `hkl`, I suggest you share some examples of properly formatted `hkl` files over on the [reciprocalspaceship repo](https://github.com/rs-station/reciprocalspaceship). I'll be happy to have a look over there, and some other lab members can probably help. I'll close this issue to be continued elsewhere.

**Comment by DorisMai** [comment]
Thank you for the fast response and intensity output feature! I'll look into reciprocalspaceship more and open an issue there if needed.
